CREATE DATABASE  DB_DATABASE;
CREATE USER DB_USER WITH REPLICATION ENCRYPTED PASSWORD 'DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE DB_DATABASE TO DB_USER;
CREATE USER DB_REPL_USER WITH REPLICATION ENCRYPTED PASSWORD 'DB_REPL_PASSWORD';
\connect DB_DATABASE
CREATE TABLE IF NOT EXISTS emails (
	id SERIAL PRIMARY KEY,
	email VARCHAR(100) UNIQUE
);
CREATE TABLE IF NOT EXISTS phones (
        id SERIAL PRIMARY KEY,
        phone_number VARCHAR(20) UNIQUE
);
INSERT INTO emails (email) VALUES ('testemail@testing.com');
INSERT INTO emails (email) VALUES ('coolemail@yandex.com');
INSERT INTO phones (phone_number) VALUES ('88005553535');
INSERT INTO phones (phone_number) VALUES ('+7(900)6667788');
